version: '2.3'

services:
  db:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql:consistent
      - ./db/mariadb.conf.d:/etc/mysql/mariadb.conf.d:cached
