version: '2.3'

services:
  web:
    build: nginx
    volumes:
      - ./nginx/http.conf:/etc/nginx/conf.d/00-http.conf:cached
      - ./nginx/vhost.conf:/etc/nginx/conf.d/99-vhost.conf:cached
      - ./nginx/ssl:/etc/nginx/ssl:cached
      - ..:/var/www/html:cached
